pre-release-commit-message = ":rocket: chore(release): version {{version}}"
shared-version = true
sign-commit = false
tag-message = "{{version}}"
tag-prefix = ""
publish = false
push = true
tag = true